# Generated by Django 3.0.4 on 2020-03-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
                ('age', models.IntegerField(default='男')),
                ('tel', models.CharField(max_length=12)),
                ('pub_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=32, unique=True)),
                ('nickname', models.CharField(max_length=32, unique=True)),
                ('focus_cities', models.TextField(default='[]')),
                ('focus_constellations', models.TextField(default='[]')),
                ('focus_stocks', models.TextField(default='[]')),
                ('key_name', models.CharField(default='abc', max_length=8)),
            ],
            options={
                'db_table': 'juheapp_user',
            },
        ),
    ]
