# Generated by Django 3.0.3 on 2020-03-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juheapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
                ('age', models.IntegerField(default='男')),
                ('tel', models.CharField(max_length=12)),
                ('pub_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['nickname'], name='nickname'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='juheapp_user',
        ),
    ]
